### ISSUE TITLE
GPIO27 Not Available to Use

### ISSUE THREAD

**Issue by GeorgeIoak** [Maschine2501/NR1-UI#3] opened 2020-09-22 00:17 UTC
When running `PreConfiguration.sh` you don't offer the choice to use GPIO27 (Pin Header #13). I don't see any reason not to be able to use it so perhaps it's just an mistake.

**Comment by Maschine2501** [comment] 2020-09-22 03:38
@GeorgeIoak Thanks for the Issue, I have forgoten to include it...

* added BCM27 to [ NR1-UI/install38conf.sh ](https://github.com/Maschine2501/NR1-UI/blob/master/install38conf.sh)

* added BCM27 to [ NR1-UI/PreConfiguration.sh ](https://github.com/Maschine2501/NR1-UI/blob/master/PreConfiguration.sh)

To re-run the Configuration steps (without running the setup aggain) just do this:

```
cd

bash  NR1-UI/PreConfiguration.sh 
```
and reboot after that!
If this is not succesfull, run it with sudo.

**Comment by Maschine2501** [comment] 2020-09-22 15:33
@GeorgeIoak Please test the steps above and give feedback ;)

**Comment by GeorgeIoak** [comment] 2020-09-22 16:05
This did let me choose GPIO27 so that is fixed.
But it again did not set the display to "No-Spectrum". I know how to fix that but this is still a bug. If I have time today I'll try to see where the problem is.

**Comment by Maschine2501** [comment] 2020-09-22 16:34
@GeorgeIoak The "No-Spectrum"-Issue is fixed now... It was caused by a missing "space" after the "=" in the [PreConfiguration.py](https://github.com/Maschine2501/NR1-UI/blob/master/ConfigurationFiles/PreConfiguration.py)...
Please retry:
```
cd

bash  NR1-UI/PreConfiguration.sh 
```

**Comment by Maschine2501** [comment] 2020-09-23 17:45
I guess  both "issues" (GPIO27 missing / "No-Spectrum") are fixed now. If not... please reopen ;)

**Closed as completed by Maschine2501** 2020-09-23 17:45 UTC
Labels: bug
